### PR TITLE
Home page: fix the introductory text

### PR DESCRIPTION
**Pull request by ericonr**
* Add PowerPC to the architecture list

* Fix punctuation

* Change "compiling" to "compiled"

### CODE REVIEW

**Comment by the-maldridge** [comment]
PowerPC is not actually a supported architecture by void.  A port is currently maintained by an individual contributor, but this is distinct from the Void project.

**Comment by ericonr** [comment]
Oh, alright! I thought its presence in xbps-src meant it was supported, because there aren't binary packages (at least that I could find) for PowerPC nor MIPS.

**Comment by the-maldridge** [comment]
The difference is that POWER support still depends on a handful of out of tree patches, whereas MIPS support depends on no such patches.

**Comment by ericonr** [comment]
Got it! Thanks :)

**Pull request merged**
