### PR TITLE
Home: make IRC channel #voidlinux a link

### PR DESCRIPTION
**Pull request by PaperMountainStudio**

### CODE REVIEW

**Comment by flexibeast** [comment]
Just wanted to mention that there used to be an IRC link, but in response to [this comment by @the-maldridge](https://github.com/void-linux/void-linux.github.io/pull/85#discussion_r389235611), it got removed in #87. :-)

**Comment by PaperMountainStudio** [comment]
> IRC link handlers aren't as widespread as they probably should be, consider stating the channel and network here rather than a blind link so people don't have to get this information from a hove over.

Now you can click the link and also see the network and channel, I think this is fine. People who do not have a client which does not support irc[s]:// links will still be able to get the information they need easily.

**Comment by Vaelatern** [comment]
I think this satisfies @the-maldridge's complaint and improves the contact information.

**Comment by Vaelatern** [comment]
However the commit message is malformed.

**Comment by PaperMountainStudio** [comment]
oh, I will fix it when I get home

**Comment by PaperMountainStudio** [comment]
fixed

**Pull request merged**
