### PR TITLE
Dark theme

### PR DESCRIPTION
**Pull request by paper42**
# Dark theme
image
# Light theme - nothing changed *
image

# Decisions that need to be made and issues which need to be addressed before this can be merged
* the void logo should be colored white on dark backgrounds? what about the Christmas logo?
* I forced the twitter box to have white background on dark theme, because it can not be easily styled - it loads its own CSS.
image
image
* doesn't the new red warning box feel out of place? is there a better color?
* should the tags `glibc` and `musl` be styled for dark theme or is this fine?
* which tab is currently selected is not as visible as on the light theme

image
search box and the dropdown menu are not styled

*) I had to remove the syntax highlighting theme solarized.css, because it did not adapt well to dark theme:
before with solarized theme:
image
after:
image
image
Syntax highlighting for a specific language was last used in 2014, so I am pretty sure we do not need to make a whole request to get this stylesheet. If this new style is not pretty enough, I can add a few lines to the CSS to make it look just like it did before.

### CODE REVIEW

**Comment by the-maldridge** [comment]
This looks really good, thanks for taking the time to do this work.  I mostly agree with all your comments, and I like the results of dropping solarized as its a bit hard to read in my opinion.  The red box looks kind of funny, maybe make it a light yellow in both modes?

**Comment by paper42** [comment]
v2:
image
* redesigned the warning box, I think it looks fine this way. Leaving it the same as in the light theme would look ugly.
* tags are now styled
* white horizontal lines are now darker
* the navbar now matches the dark version of docs.voidlinux.org
* improved the contrast of the selected tab
image
* fixed styling of inputs

two issues are sill present
* twitter background is still white, fixing this is probably not trivial, so I will leave it as it is now
* I would love to make the void logo work on dark backgrounds, but I did not find svgs in this repository

**Comment by the-maldridge** [comment]
There is an SVG copy on the wikipedia entry for Void.

**Comment by ericonr** [comment]
@paper42 everyone always forgets where the SVG is: https://alpha.de.repo.voidlinux.org/logos/

**Comment by the-maldridge** [comment]
@paper42 I'd love to get this merged, do you think you'll be able to resolve the logo concern? I'd be willing to merge as-is and do a followup if you'd prefer to do that way, but obviously my preference would be for the logo patch to make it into this PR.

**Comment by paper42** [comment]
@the-maldridge I will try looking at this PR soon. If I remember correctly, the homepage looked very bad with the original logo, so please don't merge this PR yet.

**Comment by the-maldridge** [comment]
@paper42 thanks for the heads up.  If the SVG linked above is not suitable let me know and I can try to find you another one.

**Comment by paper42** [comment]
I am quite happy how the dark logo looks, let me know what you think:
Screenshot from 2021-03-14 13-09-53
The christmas logo still looks the same. @the-maldridge do you have the svg somewhere? I can try improving it without the svg, but the result will probably be much worse.
Screenshot from 2021-03-14 13-09-19
I also changed the alert-warning, because the last one looked weird.
Screenshot from 2021-03-14 13-08-48

**Comment by paper42** [comment]
I forgot to upload the dark version of void.svg, so here it is: [void-dark.svg](https://paper.tilde.institute/void-dark.svg)

**Comment by paper42** [comment]
One small change, I replaced the outline color to match the lighter color from the logo.
Screenshot from 2021-03-14 17-08-16

**Comment by paper42** [comment]
I forgot to upload the svg, again: [void-dark2.svg](https://paper.tilde.institute/void-dark2.svg)

**Comment by the-maldridge** [comment]
I don't have the original SVG for that but @Gottox might.  In the meantime, I'm happy to merge with the knowledge that some followup has to happen to make the wreath version work right.  Worst case we completely swap out for a different wreath.

I've also copied the dark logo to the logos folder on the mirror.

**Comment by paper42** [comment]
I looked a bit into styling the embedded twitter timeline. It should be enough to add `data-theme=dark` attribute to the `<a>` element before the twitter script is loaded, but this will need some javascript, I will have to look into it.
If you are ok with the twitter timeline still being white, this PR can be merged.

**Pull request merged**
