### PR TITLE
Use https where possible

### PR DESCRIPTION
**Pull request by PaperMountainStudio**
also follow redirects

### CODE REVIEW

**Comment by the-maldridge** [comment]
Looks good but you need to resolve conflicts.

**Comment by PaperMountainStudio** [comment]
Sorry, I didn't notice, fixed.

**Comment by ericonr** [comment]
@PaperMountainStudio ping, still need to resolve conflicts. [Rebase your changes](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec)

**Comment by PaperMountainStudio** [comment]
ok, should be fine now

**Pull request merged**
