### PR TITLE
Disable christmas mode.

### PR DESCRIPTION
**Pull request by ericonr**
It can be an accessibility issue.

### CODE REVIEW

**Comment by the-maldridge** [comment]
Is there no way to have our cake and eat it too?  I said that this was pure CSS, but I'm not so sure of that now.

**Comment by Duncaen** [comment]
Its css only, but jekyll will include the css file in the template if `snow: 1`.
https://github.com/void-linux/void-linux.github.io/blob/b539f34475434aed6c4730e8f835d290fc9ae53f/_layouts/default.html#L14

**Comment by Vaelatern** [comment]
Accessibility issue? Needs citation.

**Comment by ericonr** [comment]
Someone complained on IRC that it made browsing the website terrible for them due to focus issues.

**Comment by Chocimier** [comment]
@Vaelatern: WCAG 2.1, conformance level A (lowest) requires mechanism to disable moving, blinking or scrolling of  information.
Yes, I would classify covering text with moving elements to this requirement.
No, I do not think this is real problem.

https://www.w3.org/TR/WCAG21/#pause-stop-hide

**Comment by Duncaen** [comment]
People have been complaining about it for years, I don't really see a reason to keep it despite complains.
Just need to decouple the setting from the logo:

https://github.com/void-linux/void-linux.github.io/blob/dffff813e7fc5a5fdf9652ba0be9b50d3446cd84/index.html#L9-L15

**Comment by mmnmnnmnmm** [comment]
I have ADHD and find the snow makes the website difficult to read as it can obscure the text.

This may be the correct place to use the prefers-reduced-motion css media query:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

That way people who don't mind animations can continue to enjoy the snow.

**Comment by ericonr** [comment]
@mmnmnnmnmm thank you very much for the suggestion, it does work. Do you think that property is well known? To be honest having a button would be even nicer.

**Comment by mmnmnnmnmm** [comment]
The idea is that the property is set indirectly by the browser if the
user requests reduced motion or animation from their operating system.
So the user does not need to know about the property, the browser just
respects the setting in the OS.

https://www.w3.org/TR/mediaqueries-5/#prefers-reduced-motion


It does appear to have wide support in 'modern' browsers, I know it at
least works correctly in Firefox, Chrome and Safari.

https://caniuse.com/prefers-reduced-motion
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#Browser_compatibility

**Pull request merged**
