### PR TITLE
replace gstatic fonts with local ones

### PR DESCRIPTION
**Pull request by toogley**

### CODE REVIEW

**Comment by the-maldridge** [comment]
This checks in almost a megabyte of binary data for no improvement over the way that things are done now.  As is this is not an improvement nor solving an identifiable problem, but feel free to continue the discussion here for 1) what you actually trying to accomplish and 2) the best way to accomplish this.

**Comment by the-maldridge** [comment]
Doing some basic profiling this actually hurts performance measurably, as the fonts are no longer in cache.  I also have some suspiciouns about just checking other people's fonts into a repo without any notice or license.

**Comment by toogley** [comment]
what i'm trying to accomplish is to remove the google connection. Google has a monopoly and i want to fight against it.

What do you think about just removing the google font and using the system font?

**Comment by Vaelatern** [comment]
I'd be in favor of using a system font.

**Comment by toogley** [comment]
@the-maldridge your opinion on the above?

**Comment by the-maldridge** [comment]
I see no valid reason to harm the performance of the project home page to satisfy a personal vendetta against a large company.  By that logic we shouldn't be hosting the site on GitHub pages because they're a Microsoft entity and Microsoft could be tracking your page loads.

**Comment by toogley** [comment]
@the-maldridge 
> I see no valid reason to harm the performance of the project home page to satisfy a personal vendetta against a large company.

using no external gstatic font script and instead the system font, we actually increase the performance, because the font has to be never loaded from anywhere on the internet. So yes, it will get loaded from the cache if the user vists the website a second time, but the performance will be increased the first time.

I simply see no reason to use it, the system font is likewise great. And additionally, you can see two people (one thumbs up and also @Vaelatern ) supporting this idea here. So i think many people dislike the ubiquitous presence of google, which you cannot escape properly.

This is a move to fight for a decentralized internet, where no single company has power to force people onto something they don't want. However, i agree that it is a small change.

>  By that logic we shouldn't be hosting the site on GitHub pages because they're a Microsoft entity and Microsoft could be tracking your page loads.

This is kind of true. However, i don't fear to be tracked, i just dislike that people suffer from being noticed when they are not hosted on github.

**Comment by Vaelatern** [comment]
Feel free to open a different PR to discuss switching to a system font.

**Pull request closed without merging**
