### PR TITLE
Pride Mode

### PR DESCRIPTION
**Pull request by Gottox**
image

### CODE REVIEW

**Comment by the-eater** [comment]
If I may give my input as humble contributor, and this is purely from my pov.

while I can understand keeping Void apolitical, it doesn't erase the fact that for some contributors and maintainers their existence is political at this point in time. and while people are really keen on telling me Void is "just a bunch of scripts, a build server and github CI", there's still folks maintaining it.  

I understand that it can feel cheap or cheesy, but in the current Unix climate, that in my experience is a _bit_ more bigoted, something simple as this can already mean a lot for some LGBT folks, and give some reassurance that this Linux distro isn't (completely) run by bigots. also with Void Linux not being a company that sells things, there's less of the rainbow capitalism reasoning involved, which seems to fuel most companies.

I do also want to note that strongly stating (as community or organization) that you're "apolitical" may not send the message you want to send, and is generally seen within my sphere as a giant red flag.

**Comment by Vaelatern** [comment]
@the-eater  I personally worry about the ways in which public positions can result in adverse consequences for users and contributors in move violent climates.

I'm not sure how anybody could look at our maintainers and decide that Void has any party to bigotry of any kind. If you have any personal concerns, please do feel free to reach out to any member of staff in a private message on IRC.

Void should strive to be the best distribution in the way it knows how, and not get involved in what is a functionally political matter, no matter what we all wish reality would be.

My personal suggestion would be, for this PR, that we merge the artwork, but refrain from including the mode until after further discussion within the project regarding the real-world ramifications. With this I think comes a shift in policy: We accept contributed artwork, even as the themes available on the site remain strictly controlled by Void.

**Comment by 0azizi0** [comment]
Hello Everyone and sorry in advance for any mistakes in my English.

I think it's better not to include the mode, in fact not to include any mode at all, including the christmas one. Lots of diverse thinking, backgrounds and colors out there. I prefer the focus to be specifically on Void Linux 100%. I think it's better to create a general code of conduct everone respects, so people behave good towards each other. Thanks everyone.

**Comment by tykonin** [comment]
Consider this.
If Red Hat / Gnome /Fedora, Debian, Linux Foundation and Mozilla (some or all of them did the Outreachy, "we support BLM", "We need more than deplatforming" stuff) are not doing this, maybe you are going out of your way with the virtue signaling.

**Comment by Duncaen** [comment]
> Consider this.

No.

**Comment by bugreporteur** [comment]
Why do we have to be reminded of the way other people prefer to utilize their genitals when dealing with a technical project? Don't you think the theme of genitals is already well represented in out day-to-day lives as human beings? Why haven't it come to your highly ethical mind that some people may be offended by being forced to even think about other people's genitals in such a setting? Woudln't it go against the purpose of building an "inclusive" atmosphere? 
All these questions are purely rhetorical, of course.

**Comment by the-maldridge** [comment]
The Void project recognizes that there are many facets to this discussion.  At this time we are choosing not to provide a public forum for this internal conversation due to the observed difficulty in discussing this respectfully.

**Pull request closed without merging**
